### ISSUE TITLE
XML Parsing Error: undefined entity

### ISSUE THREAD

**Issue by ahoogesteger** [Komodo/komodo-go#16]
After installing Komodo and the plugin I open preferences -> languages -> Go and see the following:

XML Parsing Error: undefined entity
Location: chrome://golang/content/pref/pref-golang.xul
Line Number 40, Column 13:

<caption label="&defaultGolangLocation.label;"/>

**Comment by toddw-as** [comment]
Which version of Komodo, and which version of the Go-lang extension was this in?

Note: I don't see this error in my testing.

**Comment by ahoogesteger** [comment]
Both the latest and the greatest from the Komodo website. Running on a
Xubuntu 14.10 x86_64 machine.
Op 4 feb. 2015 21:55 schreef "Todd Whiteman" <notifications@github.com>:

**Comment by nightwolfz** [comment]
Same error, on komodo edit 8 running on windows 10.

Line Number 40, Column 13:            <caption label="&defaultGolangLocation.label;"/>
------------^

**Comment by pcamen** [comment]
I see the same thing on Komodo Edit 8 v 8.5.4 on Mac OS X Mavericks and the latest version of the extension.

**Comment by toddw-as** [comment]
Released new version (1.3.3) - https://github.com/Komodo/komodo-go/releases/tag/1.3.3
